userlogin/basic_app/urls.py
from django.urls import path, re_path, include
from basic_app import views

app_name= 'basic_app'

urlpatterns=[
    re_path(r'^register/', views.register,name='register'),
    re_path(r'^user_login/', views.user_login, name='user_login')
]

userlogin/userlogin/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^$',views.index,name='index'),
    re_path(r'^basic_app/',include('basic_app.urls')),
    re_path(r'^logout/',views.user_logout, name='user_logout')
]

userlogin/basic_app/models.py
from django.db import models

from django.contrib.auth.models import User

# Create your models here.

class UserProfileInfo(models.Model):

    user= models.OneToOneField(User, on_delete=models.CASCADE)

    portfolio_site = models.URLField(blank=True)

    profile_pic = models.ImageField(upload_to='profile_pic', blank=True)

    def __str__(self):
        return (self.user.username)

userlogin/basic_app/forms.py
from django import forms

from basic_app.models import UserProfileInfo

from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model= User
        fields= ('email','username','password')



class UserProfileInfoForm(forms.ModelForm):
    class Meta:
        model= UserProfileInfo
        fields= ('portfolio_site','profile_pic')

userlogin/basic_app/views.py
from django.shortcuts import render

# Create your views here.
from basic_app.forms import UserForm, UserProfileInfoForm

from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from django.contrib.auth.decorators import login_required

def index(request):
    return render(request,'basic_app/index.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):

    registered= False

    if request.method=='POST':
        print("Inside POST")
        user_form= UserForm(data=request.POST)
        profile_form= UserProfileInfoForm(data=request.POST)
        print("User valid: "+ str(user_form.is_valid()))
        print("Profile valid: "+ str(profile_form.is_valid()))

        if user_form.is_valid() and profile_form.is_valid():
            print(" Inside valid")
            user= user_form.save()
            user.set_password(user.password)  # to set hashing password
            user.save()
            print("User saved")

            profile = profile_form.save(commit=False)
            profile.user=user

            if 'profile_pic' in request.FILES:
                profile.profile_pic=request.FILES['profile_pic']
            else:
                print(user_form.errors, profile_form.errors)
            profile.save()
            registered = True
            print(" registered:"+ str(registered))
    else:
        user_form = UserForm()
        profile_form=UserProfileInfoForm()

    context_dict={'registered': registered, 'profileform':profile_form,'userform':user_form}
    return render(request,'basic_app/registeration.html',context_dict)


def user_login(request):

    if request.method=='POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse(" Account not found, please register")
        else:

            print(" SOMEONE TRIED TO LOG IN WITH INVALID CREDENTIALS ")
            print("USERNAME {} and password {}".format(username,password))
            return HttpResponse(" INVALID USER CREDENTIALS")
    else:
        return render(request, 'basic_app/login.html')

userlogin/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Base</title>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
  integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

  </head>
  <body>

    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li class="navbar-brand">  <a href="{% url 'index' %}">DJANGO</a> </li>
          <li class="navbar-link">  <a href="{% url 'admin:index' %}">ADMIN</a> </li>
          <li class="navbar-link">  <a href="{% url 'basic_app:register' %}">REGISTER</a> </li>
          {% if user.is_authenticated %}
            <li class="navbar-link">  <a href="{% url 'user_logout' %}">LOGOUT</a> </li>
          {% else %}
            <li class="navbar-brand">  <a href="{% url 'basic_app:user_login' %}">LOGIn</a> </li>
          {% endif  %}


        </ul>

      </div>

    </nav>

    {% block body_block %}

    {% endblock %}

  </body>
</html>

userlogin/templates/basic_app/index.html
{% extends "basic_app/base.html" %}
{% load static %}

{% block body_block %}

<div class="container">
  <h1>Hi welcome to Home page</h1>

</div>

{% endblock %}

userlogin/templates/basic_app/login.html
{% extends "basic_app/base.html" %}
{% block body_block %}

<div class="jumbotron">

  <h1>LOGIN here</h1>

  <form  action="{% url 'basic_app:user_login' %}" method="post">
    {% csrf_token %}
    <label for="username">Username</label> <br>
    <input  type="text" name="username" value="" placeholder="User input">
    <label for="password">Password</label>
    <input type="password" name="password" value="" placeholder="Password">
    <input type="submit" class="btn btn-primary" name="" value="Login">

  </form>

</div>


{% endblock %}

userlogin/templates/basic_app/registeration.html
{% extends "basic_app/base.html" %}

{% load static %}

{% block body_block %}

<div class="jumbotron">

  {% if registered %}
    <h1>you are registered</h1>
  {% else %}
    <h1>Welcome to registration</h1>
    <h3>Register here</h3>

    <form  enctype="multipart/form-data" method="post">
      {% csrf_token %}
      {{ userform.as_p }}
      {{ profileform.as_p }}
      <input type="submit" name="" value="Register">
    </form>


  {% endif %}

</div>

{% endblock %}